[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/.well-known/assetlinks.json"
  status = 200
  force = true

  [redirects.headers]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "no-store, max-age=0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200